spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'root'
    url: jdbc:mysql://192.168.4.217:23306/multi-tenancy-demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
logging:
  level:
    com.github.deeround.jdbc.plus: info